spring.security.oauth2.resourceserver.jwt.issuer-uri:
springdoc.swagger-ui.path: "/api"

io.insee.dev.k8sonboarding:
  clusterName: "default-cluster"
  apiserver-url: "https://example.com"
  namespace-prefix: "dev-"
  namespace-group-prefix: "gr-"
  user-prefix:
  group-prefix:
  name-namespace-admin: "namespace_admin"
  insecure: "false"
  jwt:
    username-claim: "preferred_username"
  swagger:
    oauth2:
      authUrl:
      tokenUrl:
  ui:
    clientId: "clientId"
    authority: "https://my_auth_server/auth/realms/my_realm"
