spring.security.oauth2.resourceserver.jwt.issuer-uri:
springdoc.swagger-ui.path: "/api"

io.insee.dev.k8sonboarding:
  apiserver-url: "https://example.com"
  namespace-prefix: "dev-"
  user-prefix:
  name-namespace-admin: "namespace_admin"
  jwt:
    username-claim: "preferred_username"
  swagger:
    oauth2:
      authUrl:
      tokenUrl:
  ui:
    clientId: "clientId"
    keycloakUrl:
    keycloakRealm: