spring.security.oauth2.resourceserver.jwt.issuer-uri:
io.insee.dev.k8sonboarding.authorized.urls: "*"
springdoc.swagger-ui.path: "/api"

io.insee.dev.k8sonboarding:
  clusterName: "default-cluster"
  apiserver-url: "https://example.com"
  namespace-prefix: "dev-"
  namespace-group-prefix: "gr-"
  namespace-quota:
    memoryRequests: 10Gi
    cpuRequests: 8
    memoryLimits: 16Gi
    cpuLimits: 10
    storageRequests: 10Gi
    podsCount: 40
  user-prefix:
  group-prefix:
  name-namespace-admin: "namespace_admin"
  insecure: "false"
  does-remove-suffix: false
  jwt:
    username-claim: "preferred_username"
  swagger:
    oauth2:
      authUrl:
      tokenUrl:
  ui:
    clientId: "clientId"
    authority: "https://my_auth_server/auth/realms/my_realm"
    groupFilter:
    user-namespace-enabled: true
    namespace-creation-allowed: true
